### ISSUE TITLE
infinite recursion / hang on Lens.recur

### ISSUE THREAD

**Issue by binarytemple** [obrok/lens#17]
It may be that I'm just being really dumb but here goes, in the case of both the following examples, typed in the console, the terminal just hung, I'm guessing they're off on a infinite recursion loop? 

```
Lens.recur(Lens.key(:a)) |> Lens.to_list( %{a: %{b: :c}})
```

```
Lens.recur( Lens.root() |> Lens.key) |> Lens.map( %{a: %{b: :c}},  &IO.inspect/1)    
```

**Comment by obrok** [comment]
That's just because `Map.get(nil, :a)` is `nil`, so you can indeed recurse infinitely deep into a `nil` like that. I wrote most of this library a while back, can't remember if that's how it always was in Elixir, or if it changed... It's not quite clear to me if a proper fix exists that doesn't break something else. For example, we could make it so that `Lens.key(:a)` gives no results when applied to a `nil`, but that breaks the simple relationship that `Lens.to_list(Lens.key(k), m) == [m[k]]`.

**Comment by obrok** [comment]
Ah! Scratch that, I forgot how my own library works! There's `key?` for just this purpose. You can do:

```elixir
Lens.recur(Lens.key?(:a)) |> Lens.to_list(%{a: %{a: %{b: :c}}})
# => [%{b: :c}, %{a: %{b: :c}}]
```

which, I think, is what you wanted.

**Comment by binarytemple** [comment]
Thanks @obrok - that gets me over that hump, maybe for beginners the infinite recursion might be a bit non obvious, I've been having great fun playing with your library so thanks for creating it and thanks for the guidance 🙇

**Comment by obrok** [comment]
Thank you for your kind words! I'd say `Lens.recur` is a little bit more advanced (although very useful indeed) in that it's difficult to debug when things go wrong. If you'd like to make a PR adding a FAQ section to the README describing this problem and the solution, I'd be happy to merge that.
