### ISSUE TITLE
Lens.filter, error from example code

### ISSUE THREAD

**Issue by febeling** [obrok/lens#9]
There is the Svbtle article that introduces to lens, and it contains this example:
```elixir
import Integer

data = 1..10
lens = Lens.filter(&is_odd/1)

get_in(data, [lens])
# => [1, 3, 5, 7, 9]
update_in(data, [lens], &(-&1))
# => [-1, 2, -3, 4, -5, 6, -7, 8, -9, 10]
```
When I follow that in iex, line 3 using `filter/1` fails with this error:
```
iex(31)> lens = Lens.filter(&is_odd/1)
** (UndefinedFunctionError) function Lens.filter/1 is undefined or private. Did you mean one of:

      * filter/2
      * filter/3

    (lens) Lens.filter(#Function<6.99386804/1 in :erl_eval.expr/5>)
```

Which kind of makes sense, as the hex docs say it's expecting a lens as first argument. But then the article example contradicts that. What's going on? (Is that an API change?)

**Comment by obrok** [comment]
Yes, you're right, this is an API change. I basically wanted `filter/reject` to be the main filtering functions to match `Enum.filter/reject`. However, what's most often useful is filtering a previous lens instead of filtering a collection, and the version shown in the blog post is used somewhat less often in practice.

I never got around to updating that post, but perhaps I will add a note to the readme on which version it was written and how to migrate.

For now you can just use `Lens.filter(Lens.all(), function)`, to emulate the old behavior of `Lens.filter`.

**Comment by obrok** [comment]
I added a note to the README to explain the situation.
